### ISSUE TITLE
可以掘金出篇文章说说nvmd的设计与实现吗

### ISSUE THREAD

**Issue by brian4159** [1111mp/nvmd-command#10]
正在学rust 想学习学习大佬的源码

**Comment by 1111mp** [comment]
其实原理挺简单的 就是代理平时使用的 node npm 的这些命令 然后去查一下各自的安装目录然后写入到环境变量里面（执行命令的子进程的环境） 然后就可以识别了

目前客户端在使用 tauri 重构（rust） 所以你可以看一下相关的代码，目前在这个分支：https://github.com/1111mp/nvm-desktop/tree/tauri
