### ISSUE TITLE
Install node : "error decoding response body"

### ISSUE THREAD

**Issue by 09133792** [1111mp/nvmd-command#12]
在nvm desktop中安装node报错，尝试几个版本都报“error decoding response body" , 然后进度条卡住

<img width="951" alt="image" src="https://github.com/user-attachments/assets/17265e46-9f9d-4a39-83d1-1c834083c83f">

**Comment by 09133792** [comment]
NVM Desktop Version 4.0.1 (20241013.075844)
macOS Sonoma 14.6

**Comment by 09133792** [comment]
NVM Desktop Version 4.0.1 (20241013.075844)
macOS Sonoma 14.6

**Comment by 1111mp** [comment]
网络问题（大概率是代理软件的问题） 试试设置页面 使用 https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/ 镜像

**Comment by 09133792** [comment]
感谢 设置界面更改了镜像地址之后 就可以了
<img width="371" alt="image" src="https://github.com/user-attachments/assets/2f8d3487-4317-4f67-bcd2-cff320046ac2">

**Comment by 1111mp** [comment]
好的 问题解决就好 这个镜像的下拉框也可以直接输入完整镜像地址的 输入之后保存 下次就会保存作为下拉框的选项了

**Comment by 09133792** [comment]
好的 感谢大佬 工具很好用，特别是在多个项目使用不同node版本的场景下
