### ISSUE TITLE
Linux系统下命令行无法执行

### ISSUE THREAD

**Issue by ProLiok** [1111mp/nvmd-command#5]
![image](https://github.com/1111mp/nvmd-command/assets/95992064/55abec21-7f03-47b7-80f7-ce39d3f56a0c)

**Comment by 1111mp** [comment]
目前并没有专门为`Linux`编译出包，抱歉啊（主要原因是目前没有`Linux`的设备或者没安装`Linux`系统，担心其兼容性问题）。

如果可以的话请按照文档自己编译：[build-and-package](https://github.com/1111mp/nvm-desktop?tab=readme-ov-file#build-and-package)

有一点想确认一下，就是`nvm-desktop 界面程序`可以在`Linux`上成功运行吗（界面上操作`node`下载设置这些），只是终端运行`nvmd`命令报错？如果是这样的话你可以按照这样的步骤试试能不能解决：
- [Github Release v2.6.2](https://github.com/1111mp/nvmd-command/releases/tag/v2.6.2) 下载`Linux`平台的`nvmd`文件：
  <img width="1306" alt="Screenshot 2024-01-26 at 19 26 47" src="https://github.com/1111mp/nvmd-command/assets/31227919/db1be2fc-c518-4b43-8ef9-1e7e4279569d">

- 替换掉`/Applications/nvm-desktop.app/Contents/Resources/assets/sources/`目录下的`nvmd`文件（这是`macOS`系统目录，`Linux`系统的我不确定，应该类似；`assets/`是`nvm-desktop`安装后目录路径下的资源文件）：
  <img width="965" alt="Screenshot 2024-01-26 at 19 23 45" src="https://github.com/1111mp/nvmd-command/assets/31227919/828a38aa-fc20-46ce-8ac1-1a87694d3c32">

- 然后将`$HOME/.nvmd/`整个文件夹删掉
- 最后重新运行`nvm-desktop`

这样的话就会使用`Linux`平台的`nvmd`文件重新初始化了。

因为我不确定`Linux`系统的兼容性所以没有编译出正式包出来，当然`Release`界面上有`Linxu`的下载包，只不过打包的时候并没有将`nvmd`替换成`Linux`平台的，所以才会有这个问题，抱歉。

如果不嫌麻烦的话还请帮忙试试，如果这样可行的话再反馈一下，我会补出`Linux`系统的安装包出来的。

**Comment by ProLiok** [comment]
nvm-desktop 界面程序可以在Linux系统上运行，对应项目中都有正常生成.nvmdrc文件，只是其中配置node版本并没有生效，我当时感觉是这个nvmd命令行没生效，就尝试用终端运行，得出以上结果，你反馈的方法我会进行尝试并反馈的

**Comment by ProLiok** [comment]
经过尝试使用[Github Release v2.6.2](https://github.com/1111mp/nvmd-command/releases/tag/v2.6.2) 下载Linux平台的nvmd文件替换到Linux路径下~/.nvmd/bin/目录下的nvmd文件即可正常使用nvmd指令及nvmd-Desktop程序，不过nvmd-Desktop程序界面面板没有关闭按钮，通过在任务栏右键关闭会报以下错误，但不影响使用
[Github Release v2.6.2](https://github.com/1111mp/nvmd-command/releases/tag/v2.6.2) 下载Linux平台的nvmd文件：

**Comment by ProLiok** [comment]
经过尝试使用[Github Release v2.6.2](https://github.com/1111mp/nvmd-command/releases/tag/v2.6.2) 下载Linux平台的nvmd文件替换到Linux路径下~/.nvmd/bin/目录下的nvmd文件即可正常使用nvmd指令及nvmd-Desktop程序，不过nvmd-Desktop程序界面面板没有关闭按钮，通过在任务栏右键关闭会报以下错误，但不影响使用
![image](https://github.com/1111mp/nvmd-command/assets/95992064/10d7c96f-1d73-412e-8081-9611b43f8e2c)

**Comment by 1111mp** [comment]
好的 谢谢你的反馈 🌹 

后面我会修复一下`Linux`上的兼容性问题 然后补上`Linux`的安装包

**Comment by 1111mp** [comment]
最新的 [Release v3.0.0](https://github.com/1111mp/nvm-desktop/releases/tag/v3.0.0) 提供了`Linux` 的 `arm64`和`x64`架构的安装包 同时修复了兼容性问题，你可以下载试用一下。

那么我就先把这个issue给关掉了 当然后续如果有任何问题都可以随时重新打开 谢谢
