### ISSUE TITLE
npm install行不通

### ISSUE THREAD

**Issue by brian4159** [1111mp/nvmd-command#9]
npm install并不能从指定node版本上下载，运行时可以是指定的node版本

**Comment by 1111mp** [comment]
你是全局安装包还是通过package.json给项目安装依赖 正常情况下切换了node 使用的是对应node下的npm 你可以打开`nvm-desktop`的主界面查看各个node默认携带的npm的版本
![image](https://github.com/user-attachments/assets/0c1cfacb-11cf-46cf-b943-33406f5de415)

如果是全局安装包没有隔离的话 请检查npm是否设置了全局安装包的目录 可以通过 `npm config get prefix` 查看 如果设置了那么所有不同版本node的npm安装全局包都会安装到该目录下 所以就不会隔离 

更多详情请查看：https://github.com/1111mp/nvm-desktop/issues/23
